import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage({ viewport: { width: 1560, height: 1000 } });
await p.goto("http://127.0.0.1:3111", { waitUntil: "networkidle" });
await p.waitForTimeout(600);
await p.screenshot({ path: "/home/claude/shots/L1-upload.png" });
await p.setInputFiles('input[type="file"]', process.argv[2]);
await p.waitForSelector("text=Ödeme Listesi", { timeout: 45000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: "/home/claude/shots/L2-overview.png" });
await b.close();
console.log("ok");
